### ISSUE TITLE
Squirrel icon stays up after reading changelog

### ISSUE THREAD

**Issue by izuzak** [atom-archive/release-notes#36]
_From @Stanzilla on May 2, 2015 12:51_

Did I understand it correctly that the Squirrel icon in the status bar should go away after you read the changelog after updating? 

If so, the icon stays up even through me reading the changelog a few times, closing it's tab and reopening it from the icon.

If not, maybe it should go away after you read it once.

_Copied from original issue: atom/atom#6613_

**Comment by izuzak** [comment]
_From @YuriSolovyov on May 2, 2015 16:43_

Confirmed, pretty confusing

**Comment by mehcode** [comment]
On a slightly related note, I'd prefer if the squirrel icon didn't go away *until* I read it.

**Comment by izuzak** [comment]
@mehcode That might be worth opening a new issue about, if one doesn't exist.

**Comment by hannupekka** [comment]
I get this on OS X Yosemite too. Atom 0.198.0

**Comment by int3h** [comment]
:+1:

**Comment by chrishiestand** [comment]
+1

**Comment by stephwestgarth** [comment]
+1 still happening. very annoying.

**Comment by ethanluoyc** [comment]
Where is the squirrel actually loaded? I cannot seem to locate it.

**Comment by stephwestgarth** [comment]
Bottom right of the window

**Comment by ethanluoyc** [comment]
I found my way to the atom/release-packages repo and it should be updated from there is it?

**Comment by ethanluoyc** [comment]
From atom/release-notes#38, I think Ian here already fixed this but I don't know why they have not merged this.

**Comment by Foggalong** [comment]
Yeah, I'd love this. Squirrel is unneeded clutter after I've read the notes

**Comment by maahd** [comment]
+1 still happening OS X El Captain 10.11.1 (15B42) atom v. 1.2.3

**Comment by trainto** [comment]
It's still happening. Windows 7 atom v1.7.2

**Comment by winstliu** [comment]
@trainto Release Notes is no longer packaged with Atom.  Please report this on atom/about instead.

**Comment by pdostal** [comment]
But the icon is still present - is there possibility to hide it f.e. by modifying css ?

**Comment by lee-dohm** [comment]
All repositories in the [atom-archive organization](https://github.com/atom-archive) are unmaintained and deprecated. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
